name: ally
description: "Your friend in an emergency."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound/VarelaRound-Regular.ttf
          weight: 400

